events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    server {
        listen       80;          # Nginx nghe ở cổng 80 mặc định
        server_name  127.0.0.1;   # Hoặc IP máy chủ của bạn

        # 1. Nginx tự xử lý file tĩnh (Ảnh, JS, CSS) - Cực nhanh
        location /static/ {
            alias "C:/SMILE PMS/HR_PROJECT_FASTAPI/static/";
        }
	client_max_body_size 10M; # Cho phép upload file lên đến 10MB

        # 2. Đẩy toàn bộ Logic về cho FastAPI (Uvicorn)
        location / {
            proxy_pass http://127.0.0.1:6066; # Đẩy thẳng sang Python
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Hỗ trợ Websocket (nếu sau này bạn dùng FastAPI làm thông báo Realtime)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}